### PR TITLE
Use Anchors for Code

### PR DESCRIPTION
**Pull request by desttinghim**
This pull request switches the code include statements to using anchors instead of line numbers. There are a couple of other minor tweaks to the tutorial to try and clarify some bits I thought were confusing. Once merged, this pull implements the anchor part of #46, no attempt has been made to use diffs yet.

### CODE REVIEW

**Comment by desttinghim** [comment]
I've edited most of the tutorials to use the anchors. I'm going to leave out 3.4 because I think it needs some rewrites to take into account the info I brought up in #74.

**Comment by iolivia** [comment]
hey @desttinghim, this is awesome, thanks so much! do you mind splitting this into a couple of separate PRs please? maybe we can start with the first two chapters, otherwise this is a bit too big to review properly and there's a good chance some code will go missing from the book, had that before and it's a pain.

**Comment by desttinghim** [comment]
That is okay by me. Give me a bit to get the PR's up

**Comment by iolivia** [comment]
no rush at all 😄

**Comment by iolivia** [comment]
@desttinghim I just merged a PR which moves some of the files around to support translations, it might be a pain to merge directly so might be worth just starting a new branch and copying your version of the files to the new place. sorry for the hassle!

**Comment by desttinghim** [comment]
That was my plan in the first place, so no worries :)

**Comment by desttinghim** [comment]
I'll close this PR since we're going to phase out it's changes over multiple.

**Pull request closed without merging**
