### PR TITLE
Add an image cache in section 3.4

### LINKED ISSUE #89: Further performace improvements for rendering (image caching)
First of all, thank you for the awesome book! I just started learning Rust and it was fun and helpful to build the game.

I had the issue that even after implementing batch rendering the FPS were somewhere between 40 and 50, but never 60. After finishing the book I continued playing around with the code trying to reach 60 FPS. I managed by introducing a cache for the images. Now the game reaches 60 FPS after a few seconds. Would this be an addition to the book you would be interested in?

I am not sure if my implementation is well done (really new to rust), but if you are interested: 
The biggest change is https://github.com/NiklasEi/sokoban-rust/blob/master/src/systems/rendering_system.rs#L56-L63

### PR DESCRIPTION
**Pull request by NiklasEi**
Introduce an image cache in section 3.4 after batch rendering.

Resolves #89

### CODE REVIEW

**Comment by NiklasEi** [comment]
Should I propagate my code changes to 3.5 and 4.0? I am not sure what else changed since there are no chapters for those versions yet.

**Comment by NiklasEi** [comment]
What do you think about adding the cache in a separate small chapter? I can't find a way to not have an influence on the code examples in batch rendering.
If it should stay in the same chapter I could also create my own code directory for the image cache part of the chapter.

**Comment by iolivia** [comment]
@NiklasEi I think it would be a great idea to add this as a separate section to the last chapter, maybe after batch rendering. what do you think?

**Comment by NiklasEi** [comment]
> @NiklasEi I think it would be a great idea to add this as a separate section to the last chapter, maybe after batch rendering. what do you think?

So just like the current code changes?
The issue in my second comment is still not resolved though.

**Pull request closed without merging**
